# Generated by Django 4.0.4 on 2022-05-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StBoolAttribute',
            fields=[
                ('stattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.stattribute')),
                ('value', models.CharField(max_length=10, null=True)),
            ],
            bases=('knowledge_base.stattribute',),
        ),
        migrations.CreateModel(
            name='StCharAttribute',
            fields=[
                ('stattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.stattribute')),
                ('values', models.CharField(max_length=200, null=True)),
            ],
            bases=('knowledge_base.stattribute',),
        ),
        migrations.CreateModel(
            name='StIntAttribute',
            fields=[
                ('stattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.stattribute')),
                ('low_value', models.IntegerField(null=True)),
                ('high_value', models.IntegerField(null=True)),
            ],
            bases=('knowledge_base.stattribute',),
        ),
        migrations.CreateModel(
            name='IntAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('low_value', models.IntegerField(null=True)),
                ('high_value', models.IntegerField(null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='CharAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('values', models.CharField(max_length=200, null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='BoolAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('value', models.CharField(max_length=10, null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
    ]
