# Generated by Django 4.0.4 on 2022-05-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntAtribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('low_value', models.IntegerField()),
                ('high_value', models.IntegerField()),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_atrs', to='knowledge_base.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='CharAtribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('values', models.CharField(max_length=200)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_atrs', to='knowledge_base.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='BoolAtribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.BooleanField()),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_atrs', to='knowledge_base.cartype')),
            ],
        ),
    ]
