# Generated by Django 4.0.4 on 2022-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stattribute',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
