# Generated by Django 4.0.4 on 2022-05-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='charatribute',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='intatribute',
            name='car_type',
        ),
        migrations.CreateModel(
            name='BoolAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('value', models.CharField(max_length=10)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bool_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='CharAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('values', models.CharField(max_length=200)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='IntAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('low_value', models.IntegerField()),
                ('high_value', models.IntegerField()),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='StBoolAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('value', models.CharField(max_length=10)),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='StCharAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('values', models.CharField(max_length=200)),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='StIntAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('low_value', models.IntegerField()),
                ('high_value', models.IntegerField()),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.DeleteModel(
            name='BoolAtribute',
        ),
        migrations.DeleteModel(
            name='CharAtribute',
        ),
        migrations.DeleteModel(
            name='IntAtribute',
        ),
    ]
