# Generated by Django 4.0.4 on 2022-05-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_alter_stboolattribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.attribute')),
                ('low_value', models.FloatField(null=True)),
                ('high_value', models.FloatField(null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_attrs', to='knowledge_base.cartype')),
            ],
            bases=('knowledge_base.attribute',),
        ),
        migrations.CreateModel(
            name='StFloatAttribute',
            fields=[
                ('stattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.stattribute')),
                ('low_value', models.FloatField(null=True)),
                ('high_value', models.FloatField(null=True)),
            ],
            bases=('knowledge_base.stattribute',),
        ),
        migrations.RemoveField(
            model_name='stintattribute',
            name='stattribute_ptr',
        ),
        migrations.DeleteModel(
            name='IntAttribute',
        ),
        migrations.DeleteModel(
            name='StIntAttribute',
        ),
    ]
