# Generated by Django 4.0.4 on 2022-05-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_floatattribute_stfloatattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatattribute',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_attrs', to='knowledge_base.cartype'),
        ),
    ]
