# Generated by Django 4.0.4 on 2022-05-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_alter_stboolattribute_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='StInitAttribute',
            fields=[
                ('stattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge_base.stattribute')),
            ],
            options={
                'verbose_name': 'Признак',
                'verbose_name_plural': 'Признаки',
            },
            bases=('knowledge_base.stattribute',),
        ),
    ]
