# Generated by Django 4.0.4 on 2022-05-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0005_alter_floatattribute_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField()),
                ('name', models.CharField(max_length=20)),
                ('car_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='knowledge_base.cartype')),
            ],
        ),
    ]
